apiVersion: apps/v1 # apply時に使用するAPIの種別。リソース(kind)によって決まる
kind: Deployment    # Deploymentのマニフェスト
metadata:           # Deploymentのmetadata
  name: helloweb    # Deploymentリソースの名前
  labels:
    app: hello
spec:
  replicas: 3       # ReplicaSetが生成・管理するPodの数
  selector:
    matchLabels:
      app: hello    # ReplicaSetがPodを検索するときのLabel
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:1.0
          resources:               # 使用するCPU, Memoryの指定
            requests:
              cpu: 100m
              memory: 100Mi
        env:                     # 環境変数
          - name: GET_HOSTS_FROM
            value: dns
          - name: TEST_KEY
            valueFrom:
              configMapKeyRef:
                name: config-example
                key: player_initial_lives
        ports:
          - containerPort: 8080
        readinessProbe:          # ヘルスチェックの設定
          httpGet:               # ヘルスチェックでアクセスするhttpエンドポイントの情報を書く。
            path: /
            port: 8080
          initialDelaySeconds: 5 # コンテナが起動してからヘルスチェックを始めるまでの秒数。Default: 0
          timeoutSeconds: 1      # ヘルスチェックのタイムアウト秒数。最小で1秒。Default: 1
          periodSeconds: 5       # ヘルスチェックの間隔。最小で1秒。Default: 10
          successThreshold: 1    # Failure状態の時、何回成功したらSuccessになるか。最小で1回。Default: 1
        livenessProbe:           # ヘルスチェックの設定
          httpGet:               # ヘルスチェックでアクセスするhttpエンドポイントの情報を書く。
            path: /
            port: 8080
      dnsPolicy: "None"          # DNSポリシーの設定
      dnsConfig:
        nameservers:
          - 8.8.8.8

---
apiVersion: v1
kind: Service
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-example
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
