name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Yaml lint
        run: |
          docker container run --rm -v $(pwd):/data cytopia/yamllint:1.23 deployment.yml || :
